import './globals.css'
import cn from 'clsx'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Providers } from '@/components/Providers'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          'bg-background dark:bg-dark-background min-h-screen text-mn text-base transition-colors duration-500',
        )}
      >
        <Providers>
          <Header />
          <main className='relative py-6 md:py-12 w-full mx-auto max-w-screen-md px-4'>
            {/* <GoHomeButton /> */}
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
