import './globals.css'
import cn from 'clsx'
import Head from 'next/head'
import Script from 'next/script'

import { Inter } from 'next/font/google'

import type { Metadata } from 'next'
import { GoHomeButton } from '@/components/GoHomeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Script
        id='tailwind-theme'
        dangerouslySetInnerHTML={{
          __html: `if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark')
                  } else {
                    document.documentElement.classList.remove('dark')
                  }`,
        }}
      />
      <body
        className={cn(
          inter.className,
          'bg-zinc-100  min-w-full min-h-screen text-zinc-800 text-base',
        )}
      >
        <main /main>
        <main className='relative py-12 w-full mx-auto container'>
          <GoHomeButton />
          {children}
        </main>
      </body>
    </html>
  )
}
