import './globals.css'
import cn from 'clsx'

import { Inter } from 'next/font/google'

import type { Metadata } from 'next'
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          inter.className,
          'bg-zinc-50 min-w-full min-h-screen text-zinc-800 text-base'
        )}
      >
        <Header />
        <main className='py-12 w-full  mx-auto container'>{children}</main>
      </body>
    </html>
  )
}
